[build-system]
requires = ["setuptools", "wheel", "toml"]
build-backend = "setuptools.build_meta"

[project]
name = "unitree_rl_lab"
version = "0.2.0"
description = "Reinforcement Learning Lab for Unitree Robots."
